import type { ParamValues } from "@/params";

export interface BackgroundPreset {
	id: string;
	name: string;
	description: string;
	params: ParamValues;
}

const backgroundPreset = ({
	id,
	name,
	description,
	params,
}: BackgroundPreset): BackgroundPreset => ({
	id,
	name,
	description,
	params: {
		preset: "clean",
		presetId: id,
		colorA: "#10131f",
		colorB: "#f4f1e8",
		colorC: "#ffffff",
		density: 48,
		intensity: 55,
		scale: 52,
		seed: 3,
		...params,
	},
});

export const BACKGROUND_PRESETS: BackgroundPreset[] = [
	backgroundPreset({
		id: "clean",
		name: "Clean BG",
		description: "Minimal flat studio color",
		params: {
			preset: "clean",
			colorA: "#f7f7f2",
			colorB: "#dfe6ee",
			intensity: 25,
		},
	}),
	backgroundPreset({
		id: "grid",
		name: "Grid",
		description: "Editor-safe layout grid",
		params: {
			preset: "grid",
			colorA: "#0f172a",
			colorB: "#38bdf8",
			density: 56,
			intensity: 38,
		},
	}),
	backgroundPreset({
		id: "grid-waves",
		name: "Grid Waves",
		description: "Grid with flowing wave lines",
		params: {
			preset: "grid-waves",
			colorA: "#101827",
			colorB: "#22d3ee",
			colorC: "#a7f3d0",
			density: 52,
			intensity: 62,
		},
	}),
	backgroundPreset({
		id: "snow-screen",
		name: "Snow Screen Loop",
		description: "Analog TV static texture",
		params: {
			preset: "snow-screen",
			colorA: "#09090b",
			colorB: "#f8fafc",
			density: 86,
			intensity: 72,
			seed: 11,
		},
	}),
	backgroundPreset({
		id: "retro-film",
		name: "Retro Film",
		description: "Warm old-film backing",
		params: {
			preset: "retro-film",
			colorA: "#27140b",
			colorB: "#f4a261",
			colorC: "#fff3b0",
			density: 48,
			intensity: 58,
		},
	}),
	backgroundPreset({
		id: "newspaper",
		name: "Crumpled Newspaper",
		description: "Paper folds and print flecks",
		params: {
			preset: "newspaper",
			colorA: "#efe7d0",
			colorB: "#34302b",
			density: 64,
			intensity: 66,
			seed: 19,
		},
	}),
	backgroundPreset({
		id: "blueprint",
		name: "Blueprint",
		description: "Technical cyan grid",
		params: {
			preset: "grid",
			colorA: "#071a2f",
			colorB: "#60a5fa",
			density: 72,
			intensity: 44,
		},
	}),
	backgroundPreset({
		id: "studio-gray",
		name: "Studio Gray",
		description: "Soft neutral gradient",
		params: {
			preset: "clean",
			colorA: "#1f2937",
			colorB: "#9ca3af",
			intensity: 42,
		},
	}),
	backgroundPreset({
		id: "warm-paper",
		name: "Warm Paper",
		description: "Subtle warm paper texture",
		params: {
			preset: "paper",
			colorA: "#f2dfbd",
			colorB: "#7c5f3f",
			density: 52,
			intensity: 36,
		},
	}),
	backgroundPreset({
		id: "dark-paper",
		name: "Dark Paper",
		description: "Charcoal paper grain",
		params: {
			preset: "paper",
			colorA: "#141414",
			colorB: "#6b7280",
			density: 70,
			intensity: 46,
		},
	}),
	backgroundPreset({
		id: "topographic",
		name: "Topographic",
		description: "Contour map lines",
		params: {
			preset: "topographic",
			colorA: "#0b1020",
			colorB: "#84cc16",
			density: 46,
			intensity: 56,
		},
	}),
	backgroundPreset({
		id: "halftone",
		name: "Halftone",
		description: "Print-dot comic texture",
		params: {
			preset: "halftone",
			colorA: "#0f172a",
			colorB: "#facc15",
			density: 62,
			intensity: 60,
		},
	}),
	backgroundPreset({
		id: "neon-grid",
		name: "Neon Grid",
		description: "Nightlife perspective grid",
		params: {
			preset: "grid",
			colorA: "#080014",
			colorB: "#f0abfc",
			colorC: "#22d3ee",
			density: 64,
			intensity: 72,
		},
	}),
	backgroundPreset({
		id: "sunset-waves",
		name: "Sunset Waves",
		description: "Warm flowing wave bands",
		params: {
			preset: "waves",
			colorA: "#3b0a2a",
			colorB: "#fb923c",
			colorC: "#fde68a",
			density: 44,
			intensity: 68,
		},
	}),
	backgroundPreset({
		id: "ocean-waves",
		name: "Ocean Waves",
		description: "Blue water-line motion look",
		params: {
			preset: "waves",
			colorA: "#06283d",
			colorB: "#38bdf8",
			colorC: "#ccfbf1",
			density: 58,
			intensity: 54,
		},
	}),
	backgroundPreset({
		id: "aurora",
		name: "Aurora",
		description: "Soft colored light bands",
		params: {
			preset: "aurora",
			colorA: "#020617",
			colorB: "#34d399",
			colorC: "#a78bfa",
			density: 42,
			intensity: 72,
		},
	}),
	backgroundPreset({
		id: "bokeh-night",
		name: "Bokeh Night",
		description: "Soft night light dots",
		params: {
			preset: "bokeh",
			colorA: "#030712",
			colorB: "#fef3c7",
			colorC: "#f472b6",
			density: 54,
			intensity: 70,
		},
	}),
	backgroundPreset({
		id: "starfield",
		name: "Starfield",
		description: "Clean scattered stars",
		params: {
			preset: "stars",
			colorA: "#020617",
			colorB: "#e0f2fe",
			density: 72,
			intensity: 72,
			seed: 23,
		},
	}),
	backgroundPreset({
		id: "pixel-rain",
		name: "Pixel Rain",
		description: "Digital vertical pixel trails",
		params: {
			preset: "pixel-rain",
			colorA: "#03120a",
			colorB: "#22c55e",
			density: 70,
			intensity: 64,
		},
	}),
	backgroundPreset({
		id: "scanlines",
		name: "Scanlines",
		description: "Monitor-line backdrop",
		params: {
			preset: "scanlines",
			colorA: "#111827",
			colorB: "#e5e7eb",
			density: 82,
			intensity: 34,
		},
	}),
	backgroundPreset({
		id: "vhs-bars",
		name: "VHS Bars",
		description: "Retro color-bar noise",
		params: {
			preset: "vhs-bars",
			colorA: "#101010",
			colorB: "#ef4444",
			colorC: "#22d3ee",
			density: 50,
			intensity: 58,
		},
	}),
	backgroundPreset({
		id: "film-burn",
		name: "Film Burn",
		description: "Warm burned frame edges",
		params: {
			preset: "film-burn",
			colorA: "#1c0804",
			colorB: "#f97316",
			colorC: "#fef3c7",
			density: 40,
			intensity: 70,
		},
	}),
	backgroundPreset({
		id: "dust",
		name: "Dust",
		description: "Sparse dust specks",
		params: {
			preset: "dust",
			colorA: "#111111",
			colorB: "#f5f5dc",
			density: 50,
			intensity: 48,
		},
	}),
	backgroundPreset({
		id: "scratched-film",
		name: "Scratched Film",
		description: "Vertical film scratches",
		params: {
			preset: "scratches",
			colorA: "#171717",
			colorB: "#fef9c3",
			density: 58,
			intensity: 62,
		},
	}),
	backgroundPreset({
		id: "rain-glass",
		name: "Rain Glass",
		description: "Diagonal moody rain streaks",
		params: {
			preset: "rain",
			colorA: "#0f172a",
			colorB: "#93c5fd",
			density: 66,
			intensity: 58,
		},
	}),
	backgroundPreset({
		id: "snowfall",
		name: "Snowfall",
		description: "Soft falling snow dots",
		params: {
			preset: "snowfall",
			colorA: "#172033",
			colorB: "#f8fafc",
			density: 70,
			intensity: 66,
		},
	}),
	backgroundPreset({
		id: "fire-embers",
		name: "Fire Embers",
		description: "Dark ember particles",
		params: {
			preset: "embers",
			colorA: "#160806",
			colorB: "#f97316",
			colorC: "#fde047",
			density: 62,
			intensity: 76,
		},
	}),
	backgroundPreset({
		id: "smoke",
		name: "Smoke",
		description: "Layered smoky bands",
		params: {
			preset: "smoke",
			colorA: "#09090b",
			colorB: "#9ca3af",
			density: 50,
			intensity: 50,
		},
	}),
	backgroundPreset({
		id: "marble",
		name: "Marble",
		description: "Luxury stone veining",
		params: {
			preset: "marble",
			colorA: "#f8fafc",
			colorB: "#64748b",
			density: 46,
			intensity: 48,
		},
	}),
	backgroundPreset({
		id: "circuit",
		name: "Circuit",
		description: "Tech circuit board lines",
		params: {
			preset: "circuit",
			colorA: "#05130d",
			colorB: "#4ade80",
			density: 64,
			intensity: 60,
		},
	}),
	backgroundPreset({
		id: "diagonal-stripes",
		name: "Diagonal Stripes",
		description: "Clean brand stripes",
		params: {
			preset: "stripes",
			colorA: "#111827",
			colorB: "#f9fafb",
			density: 60,
			intensity: 42,
		},
	}),
	backgroundPreset({
		id: "checker",
		name: "Checker",
		description: "Bold checker texture",
		params: {
			preset: "checker",
			colorA: "#111111",
			colorB: "#fafafa",
			density: 52,
			intensity: 60,
		},
	}),
];
